version: "3.9"

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
      - ../backend/temp_audio:/app/temp_audio
      - ../backend/app.db:/app/app.db
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../frontend/.env
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
